sudo: required

language: ruby
rvm:
  - 2.2.6

services:
  - docker



env:
  global:
    - secure: "VzNgyJsh3UGcIX1PH1l5xnvF/t2w/ibLKbPqKNjJo39Qyv2lJuAX6aQBqz3iYstvBfbl7mNCPyPzUU6ucoUzRzIkfuoLkx+YBGgigwy87rFYpa56+bJXmF40+GdEAWbAruPRoT8/Y3gD9KUqn83z9UtLLQ3hXUDkr5YXzVg1YcQryHfUbJF5T31UifxXm362MJ1wlHbsY60KxGxs+IhrOEy5pwl269hhvXhnAMX8CKzN4O3HDqFNzcuISGRsDM30fvsQpLbr8Cesv1FHYkPWYXeCLfR5arFABvowHWLTtTKOBIw4M4b7a07Xct/vWc+GwPH9HT2LexkZoIxE+1ZMWr3pyYAt0ixWQWgqLr5sr/KBItYvFPc55J1bENeqQaael6928xnWxUgTbw+TNAFYnHiFtRkuLxc9Epo4gEE9sTioYmJE7i2CqaXP2XgxrIWOj45VbW0rgKc10lwaot5ex/kIQT1lw1SnV2FcFgLlCY6elsS6/hPb0PuLw/BU2Y5a43AhwJu7RHJed0GtjLDYah2gRlrh1q8UMiMPsbgZvFwJuoIeV6cW1GY0DhJrx91JPcO/20TYUI4dKdQ9AWkgsBAAJx2fWBJrqLna6ILg708iL6Ht02MUm92021SycFfj7vSgGjIHWya6TBX4Vusxa30uy6caPsxyvpEN9nL+Iis="
    - secure: "OtR23+d6KG8zN2ZDCdb6u/ewUs1DuDTDq0yJ3iMlaPPxzR7wlUvBwhJvm2wbjp4rivs86YAvX+uOkwEeYv2PjAHso1fKLcZnEWGIFhNuqTwCJi3pjMPj42w4s0G4VTmneyOmElZygj8+GeHO+MG6MetnxPeyVIl+qSOvdyX+RByMv/WHwxUaAc7nNMvE78RmuPqbpTcapWrwF9gwHock1fndLPPV6SmDj96h9+DLooq8UmBEbyQqZNipq5W6iaqEQolvpkQ0Rar5qyT2XcHHiqg+egoZ4Pyzze2xyBppTdSN+f101OYhv0XcL0a/maAnSbEJOhlXrGpqJuwZlKvo0VvRvsPu7WLgScr/ICyQSwRA01o9hqhc/sYb528Oz8gd9asVqBaK5mmBHYy8P3zwXAkhUPy73d7aUBWRNRViUg8y7q94Qg1TrBejxp4oBOAI0A0XTJHyvEz1fY6ejssGzCSogAeG67kXE6wYsx0hxFJGptVhpWZmRiJC+xGLxeFp2U+/GZOCM1/j7/oYP5hVpeteQschnRSlLE4tdDHSBQizVsYstcjRPUbc0wF8ZM5wOpUa6J/u3T48ZkDiBzGdFA05BW0O06dmQcJIRKqK9hsFCk3BnkmrQqUOrFrMCfs/dmE15Y6eKd7iq5tpeILmb/kp9ohd6hEZ+9gGdKclnDM="
    - secure: "Y8kHpAiMDmHncKTbup3KuHTIMppj9kRJKKk6B0Fp5w1e+B15NLYKL5T0ot31K3YiyIKi+GhuNFPz+u46iPMHsyCg3fKquNt1TbilWH5csibFyPLlorYi3WXPWynTIeaz0iHJi3Md6MxLiSfwB2oNeVEX21avO7eqtnswiDiEsWUzvD3wLaikrJJHRMgxfFslFKh+8i4OHoVdQLJYbFI/DiFKmbIvuEkZ0wyf+82lt9SwLm8ZwfnasimAEB48RGixdoQcNi19Qdm1HsU0TV7n+ZtHHRBzubR98WHgFHR1LyqbfhIMHWo1VU7Da7t9XTVFZvzvwe2gX6nPf8xE533TRc53iXvVoqPOTfl+l22cnV66Psomm8H1haRrZBjHChyIz1F5+ZM4GTPU5HNeY4c2xAfejOYKdr48yKyEYX7ldfK5k8zeOgDOj8w9mzVXVsM3C0GCnlkSZMNW2xDh1tzuQ9jkF2srFcVXuAglE8YTz604mh9sD6Qm9HFZlBAqCn4Rc/c3HPWqhR7zVm5NUQ96aLPrMYfmM8mFfMr6//4ylPsFVbtB4JMqcavwIs01lPiDMvhoAYQrRB1hOd73MyeRAliPnbGZasIj2ZgBhnNNGEgPhdx3wxS4R3GB7gz977yfOwMucWn6Bz4RGtc4xburLkmT5fmlBRJHk4AkElHtI/g="
    - secure: "lwGEtNminSjdoeIUa0R+H3L+yDULcSkTOPMixpf5av+YAGSVFIElG3tzWREfsy4URwObU8UXccdwnXs6ktkWdTSn75QDXNFF7T9ZXskqYAvqle6ZstIxFOypCMZ6bzXS5lFegfZ/JM/gI/Wae7ddWuWFDXQqj5E93N3wFD206jvE5aYUxXb0xXl7ntH+AOcb+qqUAEaATsaJ2lkJWjOFmLC8m4IzTk0ZaOKcr5IhelXMPB5Pfv5reUxsKs6yl17VZak5bEmq/Cdkz27fF/vaxXKBsalpqiUfVnJJFaYSa/pyhcEXTwQ9BISTBTqa5useFQzjpuLCtIBlV/x5rfvI9uYZkaQv2UzamxHATxvRklrT59HxQrEzIbeBz/7BQgzuv6tuLkP8Yl/Ax+hNj4dAy0yE60Rf6Z/LVbZFpiRqejRW2Qz5wlsffLvVZKY8B3z7Zhfd3RLu/wTadUHf2lSf3K7zcF7TyEDyVVYg53uqmfjygL2QUsluKvvZ6iJabBU4nGUpVvY8prrIP+GByYf+m+hnCiY8Bw0lZhlBOULkhW4LqKl+uB2MfcaoS9EX5RdKrVUe48P4kbnDIlFqFAmIIUVbDGO5rePeV9Gafkc05Uux0XIHNXyh2IW3ch3VzXuxdlZ4B5l/eNTDLfGrU3Z4TNftxEAXSFCWLUaJKKnWCyU="
    - BUILD_TIME=$(date  +%d.%m.%Y)
    - secure: "Ys/5svmxYRMmpj55XHz/CUnLWq/QPqcpqLIW6UeAOulPDHbVrna5oMCmSBRTvvTsy43lnfk90y6VMRlMs7pMM13Ew+S2lZYPg/eWX90EUxsWC9/Prv64wifGDE7xdjS6AmMvz0eLqDv2sIXLxav41hvADe1zjz/kSnDMj8KOM5OsMdaWrGtY7pzXvNBEQe67QkieXQmbsPuDlXbqWPugHbFf/aqRPdAQNW+2JZcIRTK1oJNQA2+A+2gixuxry103dItyWoAxn6Ubq7SXa0Npyst2xrJK7JPJmWj/B5z2DWPFwMdt2upB7yMX1j7mBXn/CBqI1StxSE2am1Rbd6Na7YYT0tNr7ixPkkG4zfp8SujwiC3jCYIqhoErinExsgLXQEMKh7lgOTpqo9UuNLZ3yVjUQEBLUJrTRDMWmpArsWjL/2BoWDL389H+NE4dg/2l/YvfTDx461pcGvPW/k7i4QJKpU34p9EM8X9NVbp6/cfjFpmx+8/C28pDCpvfaCgLwzZWulHZpPDe9YP0TsmUQO2dMP45K6Q/nxGsUWnWs/cyxbK3F+V4l551q51Dha3PkVVjc5qND6W8MuPm2n7LAFlLVk7WBpDpcHT0c0cWQRdRInyVG9dAWHJ3bFrzEmElizV56YFNx4t7HJAnDh4Z0fxj4GoChWlFJpG65xoaNrc="

before_install:
  - echo Build time is $BUILD_TIME

install:
  - gem install github_changelog_generator

before_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then

      github_changelog_generator;
      git diff --exit-code;
      
    fi
on_failure: always

# git commit -am "changelog updated";
# git push https://$GITHUB_USER:$GITHUB_PASS@github.com/funthomas424242/jenkins-pipeline.docker.git --all;


script:
  - docker build -t funthomas424242/jenkins-pipeline .
  - docker run -e "JP_WAIT_FOR_SHUTDOWN=1m" -e "JP_SCM_BRANCH_PATTERN=origin/master" -e "JP_SCM_URL=https://github.com/FunThomas424242/jenkins-pipeline.docker.git" -p 8080:8080 -p 50000:50000 funthomas424242/jenkins-pipeline
  - docker ps -a


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_TAG" !="" ]; then

      docker login -u="$BINTRAY_USER" -p="$BINTRAY_KEY" funthomas424242-docker-funthomas424242-container.bintray.io;
      docker tag funthomas424242/jenkins-pipeline funthomas424242-docker-funthomas424242-container.bintray.io/funthomas424242/jenkins-pipeline:latest;
      docker tag funthomas424242/jenkins-pipeline funthomas424242-docker-funthomas424242-container.bintray.io/funthomas424242/jenkins-pipeline:"$TRAVIS_TAG";
      docker push funthomas424242-docker-funthomas424242-container.bintray.io/funthomas424242/jenkins-pipeline;

    fi

