sudo: required

language: ruby

services:
  - docker



env:
  global:
    - secure: "Y8kHpAiMDmHncKTbup3KuHTIMppj9kRJKKk6B0Fp5w1e+B15NLYKL5T0ot31K3YiyIKi+GhuNFPz+u46iPMHsyCg3fKquNt1TbilWH5csibFyPLlorYi3WXPWynTIeaz0iHJi3Md6MxLiSfwB2oNeVEX21avO7eqtnswiDiEsWUzvD3wLaikrJJHRMgxfFslFKh+8i4OHoVdQLJYbFI/DiFKmbIvuEkZ0wyf+82lt9SwLm8ZwfnasimAEB48RGixdoQcNi19Qdm1HsU0TV7n+ZtHHRBzubR98WHgFHR1LyqbfhIMHWo1VU7Da7t9XTVFZvzvwe2gX6nPf8xE533TRc53iXvVoqPOTfl+l22cnV66Psomm8H1haRrZBjHChyIz1F5+ZM4GTPU5HNeY4c2xAfejOYKdr48yKyEYX7ldfK5k8zeOgDOj8w9mzVXVsM3C0GCnlkSZMNW2xDh1tzuQ9jkF2srFcVXuAglE8YTz604mh9sD6Qm9HFZlBAqCn4Rc/c3HPWqhR7zVm5NUQ96aLPrMYfmM8mFfMr6//4ylPsFVbtB4JMqcavwIs01lPiDMvhoAYQrRB1hOd73MyeRAliPnbGZasIj2ZgBhnNNGEgPhdx3wxS4R3GB7gz977yfOwMucWn6Bz4RGtc4xburLkmT5fmlBRJHk4AkElHtI/g="
    - secure: "lwGEtNminSjdoeIUa0R+H3L+yDULcSkTOPMixpf5av+YAGSVFIElG3tzWREfsy4URwObU8UXccdwnXs6ktkWdTSn75QDXNFF7T9ZXskqYAvqle6ZstIxFOypCMZ6bzXS5lFegfZ/JM/gI/Wae7ddWuWFDXQqj5E93N3wFD206jvE5aYUxXb0xXl7ntH+AOcb+qqUAEaATsaJ2lkJWjOFmLC8m4IzTk0ZaOKcr5IhelXMPB5Pfv5reUxsKs6yl17VZak5bEmq/Cdkz27fF/vaxXKBsalpqiUfVnJJFaYSa/pyhcEXTwQ9BISTBTqa5useFQzjpuLCtIBlV/x5rfvI9uYZkaQv2UzamxHATxvRklrT59HxQrEzIbeBz/7BQgzuv6tuLkP8Yl/Ax+hNj4dAy0yE60Rf6Z/LVbZFpiRqejRW2Qz5wlsffLvVZKY8B3z7Zhfd3RLu/wTadUHf2lSf3K7zcF7TyEDyVVYg53uqmfjygL2QUsluKvvZ6iJabBU4nGUpVvY8prrIP+GByYf+m+hnCiY8Bw0lZhlBOULkhW4LqKl+uB2MfcaoS9EX5RdKrVUe48P4kbnDIlFqFAmIIUVbDGO5rePeV9Gafkc05Uux0XIHNXyh2IW3ch3VzXuxdlZ4B5l/eNTDLfGrU3Z4TNftxEAXSFCWLUaJKKnWCyU="
    - BUILD_TIME=$(date  +%d.%m.%Y-%H:%m::%s)


before_install:
  - echo Build time is $BUILD_TIME
  - docker build -t funthomas424242/jenkins-pipeline .
  - docker run -e "JP_WAIT_FOR_SHUTDOWN=1m" -e "JP_SCM_BRANCH_PATTERN=origin/master" -e "JP_SCM_URL=https://github.com/FunThomas424242/jenkins-pipeline.docker.git" -p 8080:8080 -p 50000:50000 funthomas424242/jenkins-pipeline
  - docker ps -a



after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then

      docker login -u="$BINTRAY_USER" -p="$BINTRAY_KEY" -e funthomas424242@gmail.com funthomas424242-docker-funthomas424242-container.bintray.io

      docker tag funthomas424242/jenkins-pipeline funthomas424242-docker-funthomas424242-container.bintray.io/library/jenkins-pipeline:"$BUILD_TIME"

    fi

# docker push funthomas424242-docker-funthomas424242-container.bintray.io//jenkins-pipeline

# script:
#  - bundle exec rake test
